#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.139.128:3306/dmall_pomanage_dfkh?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
#    hikari:
#      max-lifetime: 0
#      maximum-pool-size: 20
#      minimum-idle: 5
#mybatis:
#  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath*:mappers/*.xml
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password